version: "3.4"
services:
  app:
    build: .
    networks:
      - backend

    volumes:
      - ./screenshots:/app/screenshots

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tbcounter-node
    networks:
      - backend

networks:
  backend:
    driver: bridge
