version: "3.4"
services:
  app:
    build: .
    networks:
      - backend

    volumes:
      - ./screenshots:/app/screenshots
    env_file: ".env"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tbcounter-node
      PGPORT: 7432
    networks:
      - backend
    ports:
      - 7432:7432
networks:
  backend:
    driver: bridge
